services:
  # 1. BACKEND (Python API)
  - type: web
    name: demand-api
    env: python
    # This tells Render to go into the backend folder first
    buildCommand: cd backend && pip install -r requirements.txt
    # This tells Gunicorn to look inside the backend folder for main.py
    startCommand: cd backend && gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  # 2. FRONTEND (React App)
  - type: static
    name: demand-frontend
    # This goes into the frontend folder and builds it
    buildCommand: cd frontend && npm install && npm run build
    # Point to the static files inside the frontend's build folder
    staticPublishPath: ./frontend/dist
