services:
  # 1. BACKEND (Python API)
  - type: web
    name: demand-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  # 2. FRONTEND (React App)
  - type: web
    name: demand-frontend
    env: static
    # Tell Render to go inside the frontend folder
    buildCommand: cd frontend && npm install && npm run build
    # Point to the folder created by the build (Vite uses 'dist', Create React App uses 'build')
    publishPath: ./frontend/dist
